// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnkEASBM2Gg7a_d1cT-pgCSdcbByCjcLA',
    appId: '1:718085948749:web:ab4d250e51c128adbb2304',
    messagingSenderId: '718085948749',
    projectId: 'recuerdamed-2986a',
    authDomain: 'recuerdamed-2986a.firebaseapp.com',
    storageBucket: 'recuerdamed-2986a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjzm0GPdkbi_mcL8qhC639JvQzOCzj0Ts',
    appId: '1:718085948749:android:9497a335c5ca6dbdbb2304',
    messagingSenderId: '718085948749',
    projectId: 'recuerdamed-2986a',
    storageBucket: 'recuerdamed-2986a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-3jDu0UD7iDHNMm7v2q39ClL1IV8Ev1A',
    appId: '1:718085948749:ios:c5fdddf0479901b3bb2304',
    messagingSenderId: '718085948749',
    projectId: 'recuerdamed-2986a',
    storageBucket: 'recuerdamed-2986a.firebasestorage.app',
    iosBundleId: 'com.example.recuerdamed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-3jDu0UD7iDHNMm7v2q39ClL1IV8Ev1A',
    appId: '1:718085948749:ios:c5fdddf0479901b3bb2304',
    messagingSenderId: '718085948749',
    projectId: 'recuerdamed-2986a',
    storageBucket: 'recuerdamed-2986a.firebasestorage.app',
    iosBundleId: 'com.example.recuerdamed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnkEASBM2Gg7a_d1cT-pgCSdcbByCjcLA',
    appId: '1:718085948749:web:66916385e613a261bb2304',
    messagingSenderId: '718085948749',
    projectId: 'recuerdamed-2986a',
    authDomain: 'recuerdamed-2986a.firebaseapp.com',
    storageBucket: 'recuerdamed-2986a.firebasestorage.app',
  );
}
